swagger: '2.0'

# This is your document metadata
info:
  version: "v1.0"
  title: Token Service

schemes:
  - http

basePath: /

securityDefinitions:
  basic:
    type: basic
  
definitions:
  Success:
    properties:
      access_token:
        type: string
        description: The access token
      token_type:
        type: string
        description: Bearer
      expires_in:
        type: integer
        description: Token validity in remaining seconds

# Describe your paths here
paths:
  /access_token:
    get:
      description: Get access token by giving the user info
      security:
        - basic: []
      parameters:
        - name: scope
          in: query
          description: |
              the scope(s) which is optional for user to specify, may be given
              multiple times, one scope parameter for each scope
          required: false
          type: string
        - name: json
          in: query
          description: true means return json format, everything else means only access token is returned
          required: false
          type: boolean
      # Expected responses for this operation:
      responses:
        200:
          description: Token information
          schema:
            $ref: '#/definitions/Success'
        401:
          description: Invalid credentials
        500:
          description: Unknown error